set -v

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/twoBuyer.cmx -c -impl examples/usecases/twoBuyer.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/threeBuyer.cmx -c -impl examples/usecases/threeBuyer.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/fibo.cmx -c -impl examples/usecases/fibo.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/sapNego.cmx -c -impl examples/usecases/sapNego.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/supplierInfo_microservice.cmx -c -impl examples/usecases/supplierInfo_microservice.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/sh.cmx -c -impl examples/usecases/sh.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/calc.cmx -c -impl examples/usecases/calc.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/travelAgency.cmx -c -impl examples/usecases/travelAgency.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/game.cmx -c -impl examples/usecases/game.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/mapReduce.cmx -c -impl examples/usecases/mapReduce.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/nQueen.cmx -c -impl examples/usecases/nQueen.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/santa.cmx -c -impl examples/usecases/santa.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/sleepingBarber.cmx -c -impl examples/usecases/sleepingBarber.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/smtp.cmx -c -impl examples/usecases/smtp.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/oAuth.cmx -c -impl examples/usecases/oAuth.ml)

(cd _build/default && time /Users/keigoi/.opam/4.08.0+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I examples/usecases/.test_projection.eobjs/byte -I examples/usecases/.test_projection.eobjs/native -I /Users/keigoi/.opam/4.08.0+flambda/lib/ocaml/threads -I /Users/keigoi/.opam/4.08.0+flambda/lib/stdlib-shims -I lib/.mpst.objs/byte -I lib/.mpst.objs/native -intf-suffix .ml -no-alias-deps -opaque -o examples/usecases/.test_projection.eobjs/native/dnsmini.cmx -c -impl examples/usecases/dnsmini.ml)
